
class Ship {
  constructor(name, hp, shield, power, cargo, speed, drive, cost, fuel, rapidFire){
    this.name = name;
    this.baseHp = hp;
    this.hp = hp;
    this.baseShield = shield;
    this.shield = shield;
    this.basePower = power;
    this.power = power;

    this.capacity = cargo;
    this.baseSpeed = speed;
    this.speed = speed;
    this.fuel = fuel;
    this.drive = drive;
    this.rapidFire = rapidFire; 

    // this.bonus

    this.cost = cost;
    this.pic = `./img/ships/${this.name.replace(/\s+/g, '_').toLowerCase()}.jpg`;

    
  }
}

const _ships = {
                        //        -name-          -hp-    -shld-  -pow-   -cap-       -speed-    -cost-                                                 -fuel-      -rapid fire to..-                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         -rapid fire from..-                                                      
  lightFighter    : new Ship( 'Light Fighter',    400,    10,     50,     50,         12500,      "combustionDrive",   {metal: 3000,     crystal: 1000,    deuter: 0       },  20,    {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 }],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             from: [{ target: "Cruiser", chance: 83.34 }, { target: "Deathstar", chance: 99.5 }, { target: "Pathfinder", chance: 66.67 }] }),
  heavyFighter    : new Ship( 'Heavy Fighter',    1000,   25,     150,    100,        10000,      "impulseDrive",   {metal: 6000,     crystal: 4000,    deuter: 0       },  75,    {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 }, { target: "Small Cargo", chance: 66.67 }],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   from: [{ target: "Battlecruiser", chance: 75 }, { target: "Deathstar", chance: 99 }, { target: "Pathfinder", chance: 50 }] }),
  pathfinder      : new Ship( 'Pathfinder',       2300,   100,    200,    12000,      10000,      "impulseDrive",   {metal: 8000,     crystal: 15000,   deuter: 8000    },  300,   {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 }, { target: "Cruiser", chance: 66.67 }, { target: "Light Fighter", chance: 66.67 }, { target: "Heavy Fighter", chance: 50 }],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  from: [{ target: "Battleship", chance: 80 }, { target: "Deathstar", chance: 96.67 }, { target: "Pathfinder", chance: 66.67 }] }),
  cruiser         : new Ship( 'Cruiser',          2700,   50,     400,    800,        15000,      "impulseDrive",   {metal: 20000,    crystal: 7000,    deuter: 2000    },  300,   {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 }, { target: "Light Fighter", chance: 83.34 }, { target: "Rocket Launcher", chance: 90}],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       from: [{ target: "Battleship", chance: 75 }, { target: "Deathstar", chance: 96.97 }] }),
  battleship      : new Ship( 'Battleship',       6000,   200,    1000,   1500,       10000,      "hyperspaceDrive",   {metal: 45000,    crystal: 15000,   deuter: 0       },  500,   {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 }, { target: "Pathfinder", chance: 80 }],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       from: [{ target: "Battlecruiser", chance: 85.72 }, { target: "Deathstar", chance: 96.67 }, { target: "Reaper", chance: 85.72}] }),
  battlecruiser   : new Ship( 'Battlecruiser',    7000,   400,    700,    750,        10000,      "hyperspaceDrive",   {metal: 30000,    crystal: 40000,   deuter: 15000   },  250,   {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 }, { target: "Heavy Fighter", chance: 75 }, { target: "Cruiser", chance: 75 }, { target: "Battleship", chance: 85.72 }, { target: "Small Cargo", chance: 66.67 }, { target: "Large Cargo", chance: 66.67 } ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   from: [{ target: "Destroyer", chance: 50 }, { target: "Deathstar", chance: 93.34 }] }),
  bomber          : new Ship( 'Bomber',           7500,   500,    1000,   500,        4000,       "hyperspaceDrive",   {metal: 50000,    crystal: 25000,   deuter: 15000   },  700,   {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 }, { target: "Rocket Launcher", chance: 95}, { target: "Light Laser", chance: 95}, { target: "Heavy Laser", chance: 90}, { target: "Ion Cannon", chance: 90}, { target: "Gauss Cannon", chance: 80}, { target: "Plasma Cannon", chance: 80} ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  from: [{ target: "Reaper", chance: 75 }, { target: "Deathstar", chance: 96 }] }),
  destroyer       : new Ship( 'Destroyer',        11000,  500,    2000,   2000,       5000,       "hyperspaceDrive",   {metal: 60000,    crystal: 50000,   deuter: 15000   },  1000,  {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 }, { target: "Light Laser", chance: 90}, { target: "Battlecruiser", chance: 50 }],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              from: [{ target: "Reaper", chance: 66.67 }, { target: "Deathstar", chance: 80 }] }),
  reaper          : new Ship( 'Reaper',           14000,  700,    2800,   7000,       10000,      "hyperspaceDrive",   {metal: 85000,    crystal: 55000,   deuter: 20000   },  1100,  {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 }, { target: "Battleship", chance: 85.72 }, { target: "Bomber", chance: 75 }, { target: "Destroyer", chance: 66.67 }],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          from: [{ target: "Ion Cannon", chance: 50 }, { target: "Deathstar", chance: 90 }] }),
  deathstar       : new Ship( 'Deathstar',        900000, 50000,  200000, 1000000,    100,        "hyperspaceDrive",   {metal: 5000000,  crystal: 4000000, deuter: 1000000 },  1,     {to:[{ target: "Espionage Probe", chance: 99.6 }, { target: "Solar Satellite", chance: 99.6 }, { target: "Crawler", chance: 99.6 }, { target: "Light Fighter", chance: 99.5 }, { target: "Heavy Fighter", chance: 99 }, { target: "Cruiser", chance: 96.97 }, { target: "Battleship", chance: 96.67 }, { target: "Bomber", chance: 96 }, { target: "Destroyer", chance: 80 }, { target: "Small Cargo", chance: 99.6 }, { target: "Large Cargo", chance: 99.6 }, { target: "Colony Ship", chance: 99.6 }, { target: "Recycler", chance: 99.6 }, { target: "Rocket Launcher", chance: 99.5}, { target: "Light Laser", chance: 99.5}, { target: "Heavy Laser", chance: 99}, { target: "Ion Cannon", chance: 99}, { target: "Gauss Cannon", chance: 98}, { target: "Battlecruiser", chance: 93.34}, { target: "Rocket Launcher", chance: 95}, { target: "Light Laser", chance: 95}, { target: "Heavy Laser", chance: 90}, { target: "Ion Cannon", chance: 90}, { target: "Gauss Cannon", chance: 80}, { target: "Battlecruiser", chance: 93.34}, { target: "Reaper", chance: 90}],             from: [ ] }),
  smallCargo      : new Ship( 'Small Cargo',      400,    10,     5,      5000,       5000,       "combustionDrive",   {metal: 2000,     crystal: 2000,    deuter: 0       },  20,    {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 } ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from: [{ target: "Heavy Fighter", chance: 66.67 }, { target: "Battlecruiser", chance: 66.67 }, { target: "Deathstar", chance: 99.6 }] }),
  largeCargo      : new Ship( 'Large Cargo',      1200,   25,     5,      25000,      7500,       "combustionDrive",   {metal: 6000,     crystal: 6000,    deuter: 0       },  50,    {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 } ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from: [{ target: "Battlecruiser", chance: 66.67 }, { target: "Deathstar", chance: 99.6 }] }),
  recycler        : new Ship( 'Recycler',         1600,   10,     1,      20000,      2000,       "combustionDrive",   {metal: 10000,    crystal: 6000,    deuter: 2000    },  300,   {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 } ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from: [{ target: "Deathstar", chance: 99.6 }] }),
  espionageProbe  : new Ship( 'Espionage Probe',  100,    0,      0,      0,          100000000,  "combustionDrive",   {metal: 3000,     crystal: 1000,    deuter: 0       },  1,     {to:[ ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   from: [{ target: "Light Fighter", chance: 80 }, { target: "Heavy Fighter", chance: 80 }, { target: "Cruiser", chance: 80 }, { target: "Battleship", chance: 80 }, { target: "Bomber", chance: 80 }, { target: "Destroyer", chance: 80 }, { target: "Small Cargo", chance: 80 }, { target: "Large Cargo", chance: 80 }, { target: "Colony Ship", chance: 80 }, { target: "Recycler", chance: 80 }, { target: "Battlecruiser", chance: 80}, { target: "Reaper", chance: 80}, { target: "Deathstar", chance: 96.6 }] }),
  solarSatellite  : new Ship( 'Solar Satellite',  200,    1,      1,      0,          0,          "",   {metal: 0,        crystal: 1000,    deuter: 500     },  0,     {to:[ ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   from: [{ target: "Light Fighter", chance: 80 }, { target: "Heavy Fighter", chance: 80 }, { target: "Cruiser", chance: 80 }, { target: "Battleship", chance: 80 }, { target: "Bomber", chance: 80 }, { target: "Destroyer", chance: 80 }, { target: "Small Cargo", chance: 80 }, { target: "Large Cargo", chance: 80 }, { target: "Colony Ship", chance: 80 }, { target: "Recycler", chance: 80 }, { target: "Battlecruiser", chance: 80}, { target: "Reaper", chance: 80}, { target: "Deathstar", chance: 96.6 }] }),
  colonyShip      : new Ship( 'Colony Ship',      3000,   100,    50,     7500,       2500,       "impulseDrive",   {metal: 10000,    crystal: 20000,   deuter: 10000   },  1000,  {to:[{ target: "Espionage Probe", chance: 80 }, { target: "Solar Satellite", chance: 80 }, { target: "Crawler", chance: 80 } ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from: [{ target: "Deathstar", chance: 96.6 }] }),
  crawler         : new Ship( 'Crawler',          400,    1,      1,      0,          0,          "",   {metal: 2000,     crystal: 2000,    deuter: 1000    },  0,     {to:[ ],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   from: [{ target: "Light Fighter", chance: 80 }, { target: "Heavy Fighter", chance: 80 }, { target: "Cruiser", chance: 80 }, { target: "Battleship", chance: 80 }, { target: "Bomber", chance: 80 }, { target: "Destroyer", chance: 80 }, { target: "Small Cargo", chance: 80 }, { target: "Large Cargo", chance: 80 }, { target: "Colony Ship", chance: 80 }, { target: "Recycler", chance: 80 }, { target: "Battlecruiser", chance: 80}, { target: "Reaper", chance: 80}, { target: "Deathstar", chance: 96.6 }] })
};

/**
 * [lightFighter,heavyFighter,pathfinder,cruiser,battleship,battlecruiser,bomber,destroyer,reaper,deathstar,smallCargo,largeCargo,recycler,espionageProbe,solarSatellite,colonyShip,crawler]
 */
